  name: Netology-cd

  on:
      push:
        branches:
          - main

  jobs:
    tests:
      runs-on: ubuntu-latest
      steps:
      - name: Prepare system
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install requirements
        run: |
          python3 -m pip install pip --upgrade
          pip install -r requirements.txt

      - name: Install postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '12'

      - name: Create User
        run: |
          sudo systemctl start postgresql
          postgres -c "CREATE USER admin WITH PASSWORD '1';"

      - name: Create DB
        run: postgres -c "CREATE DATABASE test;"



      - name: Run migrations
        run: python manage.py migrate

#      - name: Linting
#        run: flake8 .

      - name: Testing
        run: python manage.py test
        env:
          DB_NAME: test
          DB_HOST: localhost
          DB_PORT: 5432
          DB_user: admin
          DB_password: 1